name: Tests

on:
  push:
    branches: [ "main", "release/**" ]
    paths:
      - '**/Makefile'
      - '**.go'
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # tag=v5.0.1

    - name: Setup Go environment
      uses: actions/setup-go@v6.0.0
      with:
        # Path to the go.mod or go.work file.
        go-version-file: ./go.mod
        # Used to specify the path to a dependency file - go.sum
        cache-dependency-path: ./go.sum

    - name: Run tests
      run: CGO_ENABLED=0 make test
